version: 2.1
orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: cimg/python:3.10
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run: gradle build koverXmlReport
      - run: pip install -r rulebook-pylint/requirements.txt
      - run: pytest --cov .
      - codecov/upload

workflows:
  build-test:
    jobs:
      - build
